### ISSUE TITLE
README example doesn't work out of the box

### ISSUE THREAD

**Issue by asterite** [Codcore/Amethyst#3]
Hi!

First of all, I'm really liking your web framework! I just tried it (with a small fix) and it looks nice. It looks compact to write and has some things that made me stop and think "wait, how did he do that?".

I tried the example from the README and doing `require "amethyst"` didn't work, it can't find the `view` macro. Doing `require "amethyst/all"` did work, though, but that's not what the example says.

**Comment by Codcore** [comment]
@asterite Hello!I am really happy that you liked it, so I can say I like Crystal as well :). Thank you for feedback. This error is due to the fact that I forgot to include `Sugar::View` implicitly into the `Base::Controller` class. I'll fix it right now. 

P.S. Amethyst is very young, so there are a lot things to do.

**Comment by Codcore** [comment]
@asterite, can you tell me more about a "small fix"? It is due `require "amethyst"` or not?

**Comment by asterite** [comment]
Oh, the small fix was to use `require "amethyst/all"`. Sorry, that was a bit confusing from my part :-)

Everything's working well now. Thanks!
